import { Story, StoryId } from "./Story";

export function nextStoryId(current: StoryId): StoryId | null {
  const currentIndex = curatedStories.findIndex((story) => story.id === current);
  if (currentIndex < 0 || currentIndex === curatedStories.length - 1) {
    return null;
  }
  return curatedStories[currentIndex + 1].id;
}

export function nextStoryIdWrapping(current: StoryId): StoryId {
  const currentIndex = curatedStories.findIndex((story) => story.id === current);
  if (currentIndex < 0 || currentIndex === curatedStories.length - 1) {
    return curatedStories[0].id;
  }
  return curatedStories[currentIndex + 1].id;
}

/** A bunch of beginner stories. Generated by deep seek.
 * We can use an open source deep seek model to generate stories dynamically for the user's level.
 */
export const curatedStories: Story[] = [
  {
    id: "story-1" as StoryId,
    title: "小明的猫",
    content: `我叫小明。
我有一只猫。
我的猫很小。
我的猫是白色的。

我的猫喜欢喝牛奶。
它也喜欢吃鱼。

今天，我的猫不见了。
我很不高兴。

我看看桌子下面。猫不在。
我看看床上面。猫不在。

我听见一个声音。“喵...”
我看看门后面。

猫在那里！
我很高兴。

我的小猫也很好。
我和我的猫都很高兴。`
  },
  {
    id: "story-2" as StoryId,
    title: "小华的朋友",
    content: `

我叫小华。
我有一个朋友。
我的朋友很高。
我的朋友是中国人。

我的朋友喜欢看书。
他也喜欢听音乐。

今天，我们去学校。
我们学习中文。
中文不难，很有意思。

放学以后，我们喝茶。
我们不喝咖啡。

我和我的朋友都很高兴。`
  },
  {
    id: "story-3" as StoryId,
    title: "小红吃饭",
    content: `

我叫小红。
我喜欢吃饭。
我喜欢吃米饭和菜。
我不喜欢吃面条。

今天，妈妈在家。
妈妈做鱼和鸡蛋。
鱼很大。
鸡蛋很小。

我吃鱼和米饭。
爸爸吃鸡蛋和菜。
妈妈吃鱼和鸡蛋。

我们都吃水果。
水果很好吃。

我和爸爸妈妈都很高兴。`
  },
  {
    id: "story-4" as StoryId,
    title: "今天的天气",
    content: `

今天天气很好。
太阳很大。
没有风，也没有雨。

我和小狗去公园。
公园很近。
公园里有树和花。

我看见一个蓝鸟。
蓝鸟很小。
小狗看见一只黄蝴蝶。

我们在公园走路。
我们不跑。

今天很高兴。
小狗也很高兴。`
  }
]

export const STORY_0 = curatedStories[0]
